set(_CATKIN_CURRENT_PACKAGE "rosjava_build_tools")
set(rosjava_build_tools_VERSION "0.4.0")
set(rosjava_build_tools_MAINTAINER "Ronaldson Bellande <ronaldsonbellande@gmail.com>")
set(rosjava_build_tools_PACKAGE_FORMAT "1")
set(rosjava_build_tools_BUILD_DEPENDS "java" "ant")
set(rosjava_build_tools_BUILD_EXPORT_DEPENDS "java" "ant" "catkin")
set(rosjava_build_tools_BUILDTOOL_DEPENDS "catkin")
set(rosjava_build_tools_BUILDTOOL_EXPORT_DEPENDS )
set(rosjava_build_tools_EXEC_DEPENDS "java" "ant" "catkin")
set(rosjava_build_tools_RUN_DEPENDS "java" "ant" "catkin")
set(rosjava_build_tools_TEST_DEPENDS )
set(rosjava_build_tools_DOC_DEPENDS )
set(rosjava_build_tools_URL_WEBSITE "http://ros.org/wiki/rosjava_build_tools")
set(rosjava_build_tools_URL_BUGTRACKER "https://github.com/ros-java/rosjava_build_tools/issues")
set(rosjava_build_tools_URL_REPOSITORY "https://github.com/ros-java/rosjava_build_tools")
set(rosjava_build_tools_DEPRECATED "")