set(_CATKIN_CURRENT_PACKAGE "rosmobile_build_tools")
set(rosmobile_build_tools_VERSION "0.4.2")
set(rosmobile_build_tools_MAINTAINER "Ronaldson Bellande <ronaldsonbellande@gmail.com>")
set(rosmobile_build_tools_PACKAGE_FORMAT "1")
set(rosmobile_build_tools_BUILD_DEPENDS "java" "ant")
set(rosmobile_build_tools_BUILD_EXPORT_DEPENDS "java" "ant" "catkin")
set(rosmobile_build_tools_BUILDTOOL_DEPENDS "catkin")
set(rosmobile_build_tools_BUILDTOOL_EXPORT_DEPENDS )
set(rosmobile_build_tools_EXEC_DEPENDS "java" "ant" "catkin")
set(rosmobile_build_tools_RUN_DEPENDS "java" "ant" "catkin")
set(rosmobile_build_tools_TEST_DEPENDS )
set(rosmobile_build_tools_DOC_DEPENDS )
set(rosmobile_build_tools_URL_WEBSITE "")
set(rosmobile_build_tools_URL_BUGTRACKER "")
set(rosmobile_build_tools_URL_REPOSITORY "")
set(rosmobile_build_tools_DEPRECATED "")