#!/usr/bin/env python

"""This script creates the skeleton of an android library package"""

##############################################################################
# Imports
##############################################################################

from __future__ import print_function
import argparse
import os
import sys

from mobile_catkin_modules_build_development_tools import create_android_project
import mobile_catkin_modules_build_development_tools.console as console

##############################################################################
# Main
##############################################################################

if __name__ == "__main__":
    try:
        sys.exit(create_android_project(is_library=False))
    except Exception as e:
        console.logerror("%s : %s" % (str(e), type(e)))
        sys.exit(1)
