#!/usr/bin/env python

"""This script creates the skeleton of a rosjava catkin package (typically an entire repo)"""

##############################################################################
# Imports
##############################################################################

from __future__ import print_function
import argparse
import os
import sys

from rosjava_build_tools import init_rosjava_package
import rosjava_build_tools.console as console

##############################################################################
# Main
##############################################################################

if __name__ == "__main__":
    try:
        sys.exit(init_rosjava_package())
    except Exception as e:
        console.logerror("%s : %s" % (str(e), type(e)))
        sys.exit(1)
